# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: acd83aed305e9eccc25f361840ff86bf688b786a34e1566961b8313e1ea994a9e5c96a933ac16c22328b5c1160b2526ee3c7233d3ce3d938e3c896dfd8e05d6d

test:
  secret_key_base: 44bef025d3d2c7a0d286a718ebefad7960b1a1bde37d7418e39a4d3962f2b551fb87edc88feb4824397c76fc212eae67a4dfff932ea86caacf6562f3ca625fd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
